package viewforge.project

import viewforge.model.Project
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path

/** Why re-opening a ViewForge-generated `.kt` was refused (ADR-032). Each maps to a clear, fail-loud diagnostic. */
enum class ImportFailure {
    /** The chosen path is not an existing regular file. */
    NOT_A_FILE,

    /** The file carries no `// Generated by ViewForge` header — not our output (weak signal, checked first). */
    NOT_GENERATED,

    /** No `.viewforge/manifest.json` in any ancestor directory — the output's project metadata is missing. */
    NO_MANIFEST,

    /** The manifest exists but does not own this file's path (or is unreadable — a corrupt manifest owns nothing). */
    NOT_OWNED,

    /** The manifest owns the file, but the `.viewforge/project.vforge` IR sidecar is absent. */
    SIDECAR_MISSING,

    /** The sidecar exists but the hardened `.vforge` loader rejected it (malformed, newer schema, …). */
    SIDECAR_LOAD_FAILED,

    /** The file resolves outside its own managed root — traversal/symlink escape, refused. */
    UNSAFE_PATH,
}

/** Outcome of [ProjectImporter.open]. Never throws for an expected failure; never guesses IR from the `.kt`. */
sealed interface ImportResult {
    /**
     * The generated file was recognised and its source IR reconstructed from the sidecar. [screenId] is the
     * [viewforge.model.Screen.id] the `.kt` maps to via the manifest, or null when the manifest records no
     * mapping for it (still a valid open — the caller can fall back to the first screen).
     */
    data class Success(val project: Project, val screenId: String?) : ImportResult

    data class Failure(val kind: ImportFailure, val detail: String) : ImportResult
}

/**
 * Re-opens a `.kt` that ViewForge itself generated (ADR-032, #22) — the narrow, sanctioned exception to
 * ADR-003. The `.kt` is only an *entry point*: it is recognised (never parsed) via the ADR-029 ownership
 * manifest, and the IR is loaded wholesale from the `.viewforge/project.vforge` sidecar through the exact
 * hardened `.vforge` path ([ProjectStore.load]). Pure — no UI, no mutation; the shell (#227) turns an
 * [ImportResult] into an open document or a diagnostic.
 *
 * Recognition is deliberately fail-loud at every step (SECURITY PF-9/PF-10): a missing header, absent or
 * unreadable manifest, an unowned path, a missing/corrupt sidecar, or a path escaping its managed root each
 * refuse with a specific [ImportFailure] rather than opening a wrong or empty document.
 */
object ProjectImporter {
    /** Bytes read from the head of the `.kt` solely to check the generated-source header — never to derive IR. */
    private const val HEADER_PROBE_BYTES = 4096

    fun open(ktFile: Path): ImportResult {
        // 1. Must be a real, regular file. Resolving realpath also collapses symlinks before any confinement check.
        if (!Files.isRegularFile(ktFile)) {
            return ImportResult.Failure(ImportFailure.NOT_A_FILE, "not a regular file: $ktFile")
        }
        val realKt = try {
            ktFile.toRealPath()
        } catch (e: IOException) {
            return ImportResult.Failure(ImportFailure.NOT_A_FILE, e.message ?: "could not resolve $ktFile")
        }

        // 2. The generated-source header is a weak, forgeable recognition hint; the manifest is the authority.
        val head = try {
            readHead(realKt)
        } catch (e: IOException) {
            return ImportResult.Failure(ImportFailure.NOT_A_FILE, e.message ?: "could not read $ktFile")
        }
        if (!ExportManifest.carriesGeneratedHeader(head)) {
            return ImportResult.Failure(ImportFailure.NOT_GENERATED, "no ViewForge generated-source header")
        }

        // 3. Walk up to the nearest ancestor holding .viewforge/manifest.json — the managed output root.
        val realRoot = findManagedRoot(realKt)
            ?: return ImportResult.Failure(ImportFailure.NO_MANIFEST, "no .viewforge/manifest.json above $ktFile")

        // 4. Confinement (PF-10): the resolved file must sit inside the resolved managed root.
        if (!realKt.startsWith(realRoot)) {
            return ImportResult.Failure(ImportFailure.UNSAFE_PATH, "file escapes its managed root")
        }
        val relative = realRoot.relativize(realKt).joinToString("/")

        // 5. Ownership is manifest membership (ADR-029). A corrupt/unreadable manifest owns nothing → refuse.
        val manifest = ExportManifestStore.load(realRoot)
            ?: return ImportResult.Failure(ImportFailure.NOT_OWNED, "manifest missing or unreadable")
        if (relative !in manifest.paths) {
            return ImportResult.Failure(ImportFailure.NOT_OWNED, "$relative is not a ViewForge-owned path")
        }

        // 6. Reconstruct IR solely from the sidecar, through the hardened loader — no Kotlin is parsed.
        val sidecar = ExportManifestStore.sidecarPath(realRoot)
        if (!Files.isRegularFile(sidecar)) {
            return ImportResult.Failure(
                ImportFailure.SIDECAR_MISSING,
                "no IR sidecar at ${ExportManifest.SIDECAR_RELATIVE_PATH}",
            )
        }
        return when (val load = ProjectStore.load(sidecar)) {
            is LoadResult.Failure ->
                ImportResult.Failure(ImportFailure.SIDECAR_LOAD_FAILED, "${load.kind}: ${load.detail}")
            is LoadResult.Success ->
                ImportResult.Success(load.project, screenId = manifest.screenPaths[relative])
        }
    }

    /** Reads up to [HEADER_PROBE_BYTES] from [file] — enough for the header line, bounded against a huge input. */
    private fun readHead(file: Path): String {
        val buf = ByteArray(HEADER_PROBE_BYTES)
        val n = Files.newInputStream(file).use { it.read(buf) }
        return if (n <= 0) "" else String(buf, 0, n, StandardCharsets.UTF_8)
    }

    /** The nearest ancestor of [realKt] whose `.viewforge/manifest.json` exists, or null. Inputs are realpaths. */
    private fun findManagedRoot(realKt: Path): Path? {
        var dir: Path? = realKt.parent
        while (dir != null) {
            if (Files.isRegularFile(dir.resolve(".viewforge").resolve("manifest.json"))) return dir
            dir = dir.parent
        }
        return null
    }
}
