@file:OptIn(ExperimentalSerializationApi::class)

package viewforge.project

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import viewforge.model.Project
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path

/**
 * The record of which files a ViewForge regeneration owns in an output directory (G10, ADR-029). It is
 * written into the managed export tree as [RELATIVE_PATH] and read back on the next regeneration to know
 * exactly what ViewForge emitted last time — so re-export can replace *its own* files and remove *its own*
 * orphans while never touching anything the user authored by hand.
 *
 * It is export metadata, wholly separate from the `.vforge` document format: it has its own
 * [manifestVersion] and never travels in a project file. [paths] are project-relative, forward-slash
 * separated, exactly as the [ExportFile] bundle produced them.
 */
@Serializable
data class ExportManifest(
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    val manifestVersion: Int = MANIFEST_VERSION,
    val project: String = "",
    val paths: List<String> = emptyList(),
    /**
     * Maps a generated screen's project-relative `.kt` path to the [viewforge.model.Screen.id] it came from
     * (ADR-032) — so re-opening a recognised `.kt` can select the exact screen it corresponds to. Added in
     * manifest v2; a v1 manifest (or any without it) simply carries an empty map. Framework-agnostic: the
     * path→id pairs are supplied by the target exporter, which owns the file-naming convention.
     */
    val screenPaths: Map<String, String> = emptyMap(),
) {
    companion object {
        /** v1: paths only. v2 (ADR-032): adds [screenPaths]. Additive — a v1 manifest still loads (empty map). */
        const val MANIFEST_VERSION = 2

        /** Where the manifest lives inside a managed output directory (a namespaced dot-dir keeps the root clean). */
        const val RELATIVE_PATH = ".viewforge/manifest.json"

        /**
         * Where a regeneration stashes the source `Project` beside the manifest (ADR-032, #22): the lossless IR
         * from which the `.kt` in this directory was generated, so ViewForge can re-open its own output without
         * ever parsing Kotlin. Like [RELATIVE_PATH] this is export metadata, not a bundle path — it is not listed
         * in [paths] and is overwritten wholesale on each regeneration.
         */
        const val SIDECAR_RELATIVE_PATH = ".viewforge/project.vforge"

        /**
         * The marker ViewForge stamps on the first line of every generated source file (G6). Used as a
         * *fallback* ownership signal for a text file the manifest doesn't yet list — so regenerating over a
         * plain earlier export still recognises its own `.kt` files as owned, while genuinely user-authored
         * files (no such header) stay unowned and are refused.
         */
        const val GENERATED_HEADER_MARKER = "Generated by ViewForge"

        /** Whether [content]'s first line carries the generated-source header (G6). */
        fun carriesGeneratedHeader(content: String): Boolean =
            content.lineSequence().firstOrNull()?.contains(GENERATED_HEADER_MARKER) == true
    }
}

/**
 * The outcome of planning a regeneration (G10) — a pure diff of the new bundle against what the output
 * directory currently holds, computed by [planRegeneration]. All lists are project-relative paths.
 *
 * @property toWrite every path the new bundle will write (the whole bundle).
 * @property toDelete owned paths from the previous manifest that the new bundle no longer emits and that
 *   still exist on disk — stale output to remove (e.g. a deleted screen's file).
 * @property blocked bundle paths that exist on disk but are **not owned** (neither in the previous manifest
 *   nor carrying the generated header) — user-authored files the regeneration must not overwrite.
 */
data class RegenerationPlan(val toWrite: List<String>, val toDelete: List<String>, val blocked: List<String>)

/** The result of actually running a regeneration (G10). */
sealed interface RegenerationOutcome {
    /**
     * The regeneration was refused because writing the bundle would overwrite [unowned] files ViewForge does
     * not own. **Nothing was written or deleted** — the caller surfaces the list so the user can resolve it.
     */
    data class Blocked(val unowned: List<String>) : RegenerationOutcome

    /** The regeneration ran: [written] files were (re)written and [deleted] orphaned files were removed. */
    data class Applied(val written: List<String>, val deleted: List<String>) : RegenerationOutcome
}

/**
 * The pure core of G10 (ADR-029): diff the new [bundlePaths] against the [owned] set (previous manifest,
 * plus any header-owned files the caller folds in) and the current on-disk state ([exists]). No I/O — the
 * caller supplies disk knowledge — so the ownership rules are unit-testable without a filesystem.
 *
 * A bundle path that exists but is not owned is **blocked** (user-authored, refuse). An owned path the new
 * bundle drops and that still exists is an **orphan** to delete. Everything in the bundle is written.
 */
fun planRegeneration(bundlePaths: List<String>, owned: Set<String>, exists: (String) -> Boolean): RegenerationPlan {
    val bundle = bundlePaths.toSet()
    val blocked = bundlePaths.filter { it !in owned && exists(it) }
    val toDelete = owned.filter { it !in bundle && exists(it) }.sorted()
    return RegenerationPlan(toWrite = bundlePaths, toDelete = toDelete, blocked = blocked)
}

/**
 * Reads and writes the export [ExportManifest] inside a managed output directory (G10). Writes go through
 * the [GuardedWriter], confined to the output root (CLAUDE.md rule 6). Loading is **total** — a missing,
 * unreadable, or corrupt manifest yields null, which the regeneration treats as "nothing is owned yet": the
 * *safe* direction, since it makes every existing file unowned (refused) rather than clobberable.
 */
object ExportManifestStore {
    /** Write [manifest] into [root]/[ExportManifest.RELATIVE_PATH]. [root] is realpath-resolved for confinement. */
    fun save(manifest: ExportManifest, root: Path) {
        val realRoot = root.toRealPath()
        val text = VforgeJson.encodeToString(ExportManifest.serializer(), manifest)
        GuardedWriter.write(resolve(realRoot), text, root = realRoot)
    }

    /**
     * Stash [project] as the IR sidecar beside the manifest (ADR-032), at [root]/[ExportManifest.SIDECAR_RELATIVE_PATH].
     * Serialized with the same `.vforge` codec as a saved project, through the [GuardedWriter] (root-confined), so
     * re-opening it later runs the identical hardened load path — no separate format, no Kotlin parsing.
     */
    fun saveSidecar(project: Project, root: Path) {
        val realRoot = root.toRealPath()
        GuardedWriter.write(sidecarPath(realRoot), ProjectCodec.encode(project), root = realRoot)
    }

    /** The IR-sidecar path inside [root] (resolved segment-by-segment, cross-platform). May not exist. */
    fun sidecarPath(root: Path): Path = resolveRelative(root, ExportManifest.SIDECAR_RELATIVE_PATH)

    /** The manifest in [root], or null when absent or unreadable (never throws). */
    fun load(root: Path): ExportManifest? {
        val file = resolve(root)
        if (!Files.exists(file)) return null
        return try {
            VforgeJson.decodeFromString(ExportManifest.serializer(), Files.readString(file, StandardCharsets.UTF_8))
        } catch (_: IOException) {
            null
        } catch (_: SerializationException) {
            null
        } catch (_: IllegalArgumentException) {
            null
        }
    }

    private fun resolve(root: Path): Path = resolveRelative(root, ExportManifest.RELATIVE_PATH)

    private fun resolveRelative(root: Path, relative: String): Path =
        relative.split('/').fold(root) { acc, segment -> acc.resolve(segment) }
}
