# JVM args for the Gradle daemon. Compose/KotlinPoet builds are memory-hungry.
org.gradle.jvmargs=-Xmx3g -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.code.style=official

# Compose Multiplatform
org.jetbrains.compose.experimental.jscanvas.enabled=false
