package viewforge.packages.compose.codegen

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ParameterSpec
import viewforge.model.Project
import viewforge.model.Screen
import viewforge.model.Theme
import viewforge.spi.CodeGenerator
import viewforge.spi.GeneratedFile

/**
 * The Compose framework package's [CodeGenerator] (ARCHITECTURE §6.2, §7) — the one SPI implementation
 * until Phase 5 (ADR-007). Lowers a [Project] to idiomatic Kotlin/Compose source, one `@Composable`
 * per screen, via KotlinPoet's structural API only (GC-1). No disk access: writing is the guarded
 * writer's job (CLAUDE.md rule 6).
 *
 * Each generated file carries a header naming its source (GC-5) and takes the conventional
 * `modifier: Modifier = Modifier` parameter, onto which the root node's own chain is applied so the
 * caller's modifier comes first (DATA_MODEL §12.1).
 */
class ComposeCodeGenerator : CodeGenerator {
    override fun generate(project: Project): List<GeneratedFile> {
        val sourceName = project.name.ifBlank { "Project" }
        return project.screens.map { screen ->
            GeneratedFile(
                path = "${KotlinIdentifiers.requireFunctionName(screen.name)}.kt",
                content = generateScreen(screen, project.theme, sourceName, project.schemaVersion),
            )
        }
    }

    /** Generates the source text for a single [screen]; also the unit the golden tests assert on. */
    fun generateScreen(screen: Screen, theme: Theme, sourceName: String, schemaVersion: Int): String {
        val fnName = KotlinIdentifiers.requireFunctionName(screen.name)
        val function = FunSpec.builder(fnName)
            .addAnnotation(ComposeNames.Composable)
            .addParameter(
                ParameterSpec.builder("modifier", ComposeNames.Modifier)
                    .defaultValue("%T", ComposeNames.Modifier)
                    .build(),
            )
            .apply {
                // A hidden root excludes the whole tree from output (DATA_MODEL §5) — an empty body.
                if (!screen.root.hidden) {
                    addCode("%L\n", ComponentEmitter(theme).emit(screen.root, isRoot = true))
                }
            }
            .build()

        return FileSpec.builder("", fnName)
            // KotlinPoet converts `·` (its non-breaking-space marker, TECHNICAL_NOTES §9) to a plain
            // space anywhere in output, so the source line uses a parenthesised separator instead.
            .addFileComment(
                "Generated by ViewForge — do not edit.\n%L",
                "Source: $sourceName.vforge (schema $schemaVersion)",
            )
            .indent("    ") // 4 spaces — Kotlin convention (KotlinPoet defaults to 2).
            .addFunction(function)
            .build()
            .toString()
    }
}
