package viewforge.packages.compose.codegen

import viewforge.model.Asset

/**
 * How an `Image` node's asset is emitted (#223, ADR-021). Codegen supports two strategies because the two
 * export shapes need different resource APIs:
 *
 * - [Desktop] — the Phase-1 desktop `androidx.compose.ui.res.painterResource("<path>")`, reading a classpath
 *   resource. Self-contained (no Gradle plugin), so the in-process compile gate compiles it; it is the
 *   default, and the desktop-only export ([viewforge.packages.compose.targets.DesktopExporter]) keeps it.
 * - [Multiplatform] — the Compose Multiplatform `org.jetbrains.compose.resources.painterResource(Res.drawable.x)`,
 *   which *is* a `commonMain` API, so an image renders on Android too. The `Res` accessor is generated by the
 *   resources Gradle plugin from files under `commonMain/composeResources/drawable/`, in [resPackage]
 *   (configured on the scaffold so it is deterministic). The KMP export
 *   ([viewforge.packages.compose.targets.MultiplatformExporter]) uses this.
 *
 * `Res.drawable` output cannot be compiled by the in-process gate — the plugin can't run inside
 * kotlin-compile-testing and `DrawableResource` has an internal constructor (ADR-021) — so it is verified
 * structurally (golden + exporter tests) and by a real Gradle build, like the rest of the KMP scaffold (#218).
 */
sealed interface ImageResources {
    object Desktop : ImageResources

    data class Multiplatform(val resPackage: String) : ImageResources
}

/**
 * Maps an [Asset] to its Compose Multiplatform drawable identity (#223): the `Res.drawable.<accessor>` name and
 * the `composeResources/drawable/<file>` file the resources plugin turns into that accessor. Both the emitter
 * (which references the accessor) and the exporter (which places the file) derive from here, so they agree.
 *
 * The accessor is the asset's file name (sans extension), lowercased and reduced to a legal Kotlin/resource
 * identifier (`[a-z0-9_]`, never leading-digit). Distinct source names normally yield distinct accessors; two
 * assets whose names collapse to the same identifier would collide, which a future import-time check can guard.
 */
object DrawableResources {
    fun accessor(asset: Asset): String {
        val base = asset.path.substringAfterLast('/').substringBeforeLast('.')
        val sanitized = base.lowercase().map {
            if (it in 'a'..'z' ||
                it in '0'..'9' ||
                it == '_'
            ) {
                it
            } else {
                '_'
            }
        }.joinToString("")
        val nonBlank = sanitized.ifBlank { "img" }
        return if (nonBlank.first().isDigit()) "img_$nonBlank" else nonBlank
    }

    /** The drawable file name (accessor + original extension), placed under `composeResources/drawable/`. */
    fun fileName(asset: Asset): String {
        val ext = asset.path.substringAfterLast('.', "")
        return if (ext.isBlank()) accessor(asset) else "${accessor(asset)}.${ext.lowercase()}"
    }
}
