package viewforge.packages.compose.codegen

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import viewforge.model.Theme
import viewforge.packages.compose.render.MATERIAL_COLOR_SLOTS
import viewforge.packages.compose.render.MATERIAL_SHAPE_SLOTS

/**
 * Emits the project theme as a `Theme.kt` with a reusable `@Composable AppTheme(darkTheme, content)`
 * wrapper (H4, DATA_MODEL §8) — the code twin of the canvas's `projectColorScheme`/`projectShapes`
 * (ADR-018), so a screen looks the same compiled as it does on the canvas. Built entirely with
 * KotlinPoet's structural API (GC-1).
 *
 * The wrapper overlays the project's Material-named tokens onto the Material defaults: `colors.<slot>`
 * → the light/dark [androidx.compose.material3.ColorScheme] slots, Material-named `typography.<slot>`
 * → a [androidx.compose.material3.Typography], `shapes.small|medium|large` → a
 * [androidx.compose.material3.Shapes]. Custom (non-Material) color/typography tokens are not part of
 * MaterialTheme; they are emitted inline where a prop references them (`CodegenValues`). `spacing`,
 * which is not a Material concept, generates as a simple `AppSpacing` object (DATA_MODEL §8).
 */
internal object ThemeEmitter {
    private val Dp = ClassName("androidx.compose.ui.unit", "Dp")

    /** The `Theme.kt` source for [theme], or null when the theme defines nothing worth emitting. */
    fun generate(theme: Theme, sourceName: String, schemaVersion: Int): String? {
        if (theme.colors.isEmpty() && theme.typography.isEmpty() && theme.shapes.isEmpty() && theme.spacing.isEmpty()) {
            return null
        }

        val file = FileSpec.builder("", "Theme")
            .addFileComment(
                "Generated by ViewForge — do not edit.\n%L",
                "Source: $sourceName.vforge (schema $schemaVersion)",
            )
            .indent("    ")
            .addProperty(colorSchemeProperty("LightColors", theme, dark = false))
            .addProperty(colorSchemeProperty("DarkColors", theme, dark = true))
            .apply {
                typographyProperty(theme)?.let { addProperty(it) }
                shapesProperty(theme)?.let { addProperty(it) }
                spacingObject(theme)?.let { addType(it) }
            }
            .addFunction(appThemeFunction(theme))
            .build()
            .toString()
        return KotlinFormatter.format(file)
    }

    // --- colors -----------------------------------------------------------------------------------

    private fun colorSchemeProperty(name: String, theme: Theme, dark: Boolean): PropertySpec =
        PropertySpec.builder(name, ComposeNames.ColorScheme)
            .addModifiers(KModifier.PRIVATE)
            .initializer(colorSchemeInit(theme, dark))
            .build()

    private fun colorSchemeInit(theme: Theme, dark: Boolean): CodeBlock {
        val factory = if (dark) ComposeNames.darkColorScheme else ComposeNames.lightColorScheme
        val slots = MATERIAL_COLOR_SLOTS.filter { it in theme.colors }
        if (slots.isEmpty()) return CodeBlock.of("%M()", factory)
        val b = CodeBlock.builder().add("%M(\n", factory).indent()
        slots.forEach { slot ->
            val pair = theme.colors.getValue(slot)
            b.add("%L = %L,\n", slot, CodegenValues.colorLiteral(if (dark) pair.dark else pair.light))
        }
        return b.unindent().add(")").build()
    }

    // --- typography (Material-named slots only) ---------------------------------------------------

    private fun typographyProperty(theme: Theme): PropertySpec? {
        val slots = theme.typography.filterKeys { it in CodegenValues.MATERIAL_TYPO_SLOTS }
        if (slots.isEmpty()) return null
        val b = CodeBlock.builder().add("%T(\n", ComposeNames.Typography).indent()
        slots.forEach { (slot, token) -> b.add("%L = %L,\n", slot, CodegenValues.textStyle(token)) }
        b.unindent().add(")")
        return PropertySpec.builder("AppTypography", ComposeNames.Typography)
            .addModifiers(KModifier.PRIVATE)
            .initializer(b.build())
            .build()
    }

    // --- shapes -----------------------------------------------------------------------------------

    private fun shapesProperty(theme: Theme): PropertySpec? {
        val slots = MATERIAL_SHAPE_SLOTS.filter { it in theme.shapes }
        if (slots.isEmpty()) return null
        val b = CodeBlock.builder().add("%T(\n", ComposeNames.Shapes).indent()
        slots.forEach { slot ->
            b.add(
                "%L = %M(%L.%M),\n",
                slot,
                ComposeNames.RoundedCornerShape,
                theme.shapes.getValue(slot),
                ComposeNames.dp,
            )
        }
        b.unindent().add(")")
        return PropertySpec.builder("AppShapes", ComposeNames.Shapes)
            .addModifiers(KModifier.PRIVATE)
            .initializer(b.build())
            .build()
    }

    // --- spacing (a plain object; not a Material concept) -----------------------------------------

    private fun spacingObject(theme: Theme): TypeSpec? {
        if (theme.spacing.isEmpty()) return null
        val obj = TypeSpec.objectBuilder("AppSpacing")
        theme.spacing.forEach { (name, dp) ->
            obj.addProperty(
                PropertySpec.builder(name, Dp)
                    .initializer("%L.%M", dp, ComposeNames.dp)
                    .build(),
            )
        }
        return obj.build()
    }

    // --- the wrapper ------------------------------------------------------------------------------

    private fun appThemeFunction(theme: Theme): FunSpec {
        val contentLambda = LambdaTypeName.get(returnType = UNIT)
            .copy(annotations = listOf(AnnotationSpec.builder(ComposeNames.Composable).build()))
        val call = CodeBlock.builder()
            .add("%T(\n", ComposeNames.MaterialTheme)
            .indent()
            .add("colorScheme = if (darkTheme) DarkColors else LightColors,\n")
            .apply {
                if (theme.typography.keys.any { it in CodegenValues.MATERIAL_TYPO_SLOTS }) {
                    add("typography = AppTypography,\n")
                }
                if (MATERIAL_SHAPE_SLOTS.any { it in theme.shapes }) add("shapes = AppShapes,\n")
            }
            .add("content = content,\n")
            .unindent()
            .add(")\n")
            .build()

        return FunSpec.builder("AppTheme")
            .addAnnotation(ComposeNames.Composable)
            .addParameter(
                ParameterSpec.builder("darkTheme", com.squareup.kotlinpoet.BOOLEAN)
                    .defaultValue("%M()", ComposeNames.isSystemInDarkTheme)
                    .build(),
            )
            .addParameter("content", contentLambda)
            .addCode(call)
            .build()
    }
}
