package viewforge.packages.compose.targets

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.TypeSpec
import viewforge.model.Project
import viewforge.packages.compose.codegen.KotlinFormatter
import viewforge.packages.compose.codegen.KotlinIdentifiers
import viewforge.packages.compose.codegen.NavHost

/**
 * The generated **platform entry points** for an exported Compose project — the small per-target files
 * that stand up a window/activity and render the project's first screen. The shared screens themselves
 * come from [viewforge.packages.compose.codegen.ComposeCodeGenerator] and are framework-neutral
 * `commonMain`; only these entry points differ per target (ADR-008/ADR-036).
 *
 * Both are built with KotlinPoet's structural API (CLAUDE.md rule 4) and passed through the G7
 * [KotlinFormatter], and both are emitted in the **default package** — the screens, `Theme`, and these
 * entry points all live there, so an entry point references `AppTheme`/`<Screen>` directly (Kotlin does
 * not allow importing default-package declarations into a *named* package, so keeping everything in the
 * default package avoids forcing a package onto the screen codegen).
 */
internal object ComposeEntryPoints {
    /** The desktop entry-point file name (`jvmMain`), also the class Gradle runs (`mainClass = "MainKt"`). */
    const val MAIN_KT = "Main.kt"

    /** The Android entry-point file name (`androidMain`); the manifest points its launcher activity here. */
    const val MAIN_ACTIVITY_KT = "MainActivity.kt"

    private val application = MemberName("androidx.compose.ui.window", "application")
    private val windowFn = MemberName("androidx.compose.ui.window", "Window")
    private val setContent = MemberName("androidx.activity.compose", "setContent")
    private val materialTheme = MemberName("androidx.compose.material3", "MaterialTheme")

    /** The generated project theme wrapper (`Theme.kt`), in the same default package as the screens. */
    private val appTheme = MemberName("", "AppTheme")

    private val componentActivity = ClassName("androidx.activity", "ComponentActivity")
    private val bundle = ClassName("android.os", "Bundle")

    /**
     * The desktop `main()` (`jvmMain`): opens an [application] [windowFn], wraps the first screen in the
     * project's [appTheme] wrapper when [themed] (else a default [materialTheme]), and renders it. With no
     * screens it opens an empty themed window rather than failing.
     */
    fun desktopMain(project: Project, themed: Boolean): String {
        val entry = entryComposable(project)
        val title = project.name.ifBlank { "ViewForge" }
        val theme = if (themed) appTheme else materialTheme
        val body = CodeBlock.builder()
            .beginControlFlow("%M", application)
            .beginControlFlow("%M(onCloseRequest = ::exitApplication, title = %S)", windowFn, title)
            .apply {
                if (entry != null) {
                    beginControlFlow("%M", theme)
                    addStatement("%M()", entry)
                    endControlFlow()
                } else {
                    addStatement("%M { }", theme)
                }
            }
            .endControlFlow()
            .endControlFlow()
            .build()

        val file = FileSpec.builder("", "Main")
            .addFileComment("Generated by ViewForge — do not edit.\n%L", sourceLine(project))
            .indent("    ")
            .addFunction(FunSpec.builder("main").addCode(body).build())
            .build()
            .toString()
        return KotlinFormatter.format(file)
    }

    /**
     * The Android `MainActivity` (`androidMain`): a `ComponentActivity` whose `onCreate` calls
     * [setContent], wrapping the first screen in the [appTheme] wrapper when [themed] (else a default
     * [materialTheme]). Emitted in the default package so it sees the `commonMain` `AppTheme`/`<Screen>`
     * (androidMain depends on commonMain); the manifest binds it by the fully-qualified name `MainActivity`.
     */
    fun androidMainActivity(project: Project, themed: Boolean): String {
        val entry = entryComposable(project)
        val theme = if (themed) appTheme else materialTheme
        val onCreate = FunSpec.builder("onCreate")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("savedInstanceState", bundle.copy(nullable = true))
            .addStatement("super.onCreate(savedInstanceState)")
            .beginControlFlow("%M", setContent)
            .apply {
                if (entry != null) {
                    beginControlFlow("%M", theme)
                    addStatement("%M()", entry)
                    endControlFlow()
                } else {
                    addStatement("%M { }", theme)
                }
            }
            .endControlFlow()
            .build()

        val activity = TypeSpec.classBuilder("MainActivity")
            .superclass(componentActivity)
            .addFunction(onCreate)
            .build()

        val file = FileSpec.builder("", "MainActivity")
            .addFileComment("Generated by ViewForge — do not edit.\n%L", sourceLine(project))
            .indent("    ")
            .addType(activity)
            .build()
            .toString()
        return KotlinFormatter.format(file)
    }

    /**
     * The composable an entry point renders: the generated [NavHost.APP_FN] host when the project has any
     * screen-to-screen navigation (ADR-039, #214) — so the entry stands up the screen switcher — else the first
     * screen directly (byte-identical to before navigation existed), or null when the project has no screens.
     */
    private fun entryComposable(project: Project): MemberName? = when {
        NavHost.projectNavigates(project) -> MemberName("", NavHost.APP_FN)
        else -> project.screens.firstOrNull()?.let { MemberName("", KotlinIdentifiers.requireFunctionName(it.name)) }
    }

    private fun sourceLine(project: Project): String =
        "Source: ${project.name.ifBlank { "Project" }}.vforge (schema ${project.schemaVersion})"
}
