package viewforge.packages.compose.targets

import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.MemberName
import viewforge.model.Project
import viewforge.packages.compose.codegen.ComposeCodeGenerator
import viewforge.packages.compose.codegen.KotlinFormatter
import viewforge.packages.compose.codegen.KotlinIdentifiers
import viewforge.project.BinaryFile
import viewforge.project.ExportFile
import viewforge.project.TextFile

/**
 * The Compose **desktop** target exporter (repo layout §4, ADR-008: one package, N targets). It turns
 * a [Project] into a ready-to-write [ExportFile] bundle in one of two shapes:
 *
 * - [looseFiles] — just the generated `@Composable` screens (G4), for pasting into an existing project.
 * - [gradleProject] — a full, runnable Compose Desktop scaffold (G5): the screens under
 *   `src/main/kotlin`, a generated `Main.kt` entry point, Gradle build scripts, and the Gradle
 *   wrapper, so `./gradlew run` works unmodified.
 *
 * Pure by design — it returns bytes, never touches disk. Writing (with overwrite confirmation and the
 * path guard) is [viewforge.project.ProjectExporter]'s job. All generated Kotlin is built with
 * KotlinPoet and passed through the [KotlinFormatter] G7 pass (ADR-018); the build-config text comes
 * from [GradleScaffold]. The Gradle wrapper jar and `gradlew` scripts are copied verbatim from the
 * checksum-verified copies bundled with ViewForge (SECURITY DS-5), never re-synthesized.
 */
object DesktopExporter {
    private const val SOURCE_DIR = "src/main/kotlin"

    private val application = MemberName("androidx.compose.ui.window", "application")
    private val windowFn = MemberName("androidx.compose.ui.window", "Window")
    private val materialTheme = MemberName("androidx.compose.material3", "MaterialTheme")

    /** The generated screen composables only (G4), each formatted, at top level (default package). */
    fun looseFiles(project: Project): List<ExportFile> = screenFiles(project, dir = "")

    /** A complete runnable Compose Desktop project (G5). */
    fun gradleProject(project: Project): List<ExportFile> {
        val slug = GradleScaffold.slug(project.name.ifBlank { "Project" })
        return buildList {
            addAll(screenFiles(project, dir = "$SOURCE_DIR/"))
            add(TextFile("$SOURCE_DIR/Main.kt", mainSource(project)))
            add(TextFile("build.gradle.kts", GradleScaffold.buildGradle()))
            add(TextFile("settings.gradle.kts", GradleScaffold.settingsGradle(slug)))
            add(TextFile("gradle.properties", GradleScaffold.gradleProperties()))
            add(TextFile(".gitignore", GradleScaffold.gitignore()))
            add(TextFile("README.md", GradleScaffold.readme(project.name.ifBlank { "Project" })))
            add(TextFile("gradle/wrapper/gradle-wrapper.properties", GradleScaffold.wrapperProperties()))
            add(BinaryFile("gradle/wrapper/gradle-wrapper.jar", resource("gradle-wrapper.jar")))
            add(BinaryFile("gradlew", resource("gradlew"), executable = true))
            add(BinaryFile("gradlew.bat", resource("gradlew.bat")))
        }
    }

    /** Runs codegen (reusing the same emitter the canvas mirrors) and the G7 formatter over each screen. */
    private fun screenFiles(project: Project, dir: String): List<TextFile> =
        ComposeCodeGenerator().generate(project).map { generated ->
            TextFile("$dir${generated.path}", KotlinFormatter.format(generated.content))
        }

    /**
     * The scaffold's `main()` entry point, built structurally (CLAUDE.md rule 4): it opens a desktop
     * [windowFn], wraps content in a default [materialTheme] (theme codegen is M8/H4), and renders the
     * project's first screen. With no screens it opens an empty themed window rather than failing.
     */
    private fun mainSource(project: Project): String {
        val firstScreen = project.screens.firstOrNull()
        val title = project.name.ifBlank { "ViewForge" }
        val body = CodeBlock.builder()
            .beginControlFlow("%M", application)
            .beginControlFlow("%M(onCloseRequest = ::exitApplication, title = %S)", windowFn, title)
            .apply {
                if (firstScreen != null) {
                    val screenFn = MemberName("", KotlinIdentifiers.requireFunctionName(firstScreen.name))
                    beginControlFlow("%M", materialTheme)
                    addStatement("%M()", screenFn)
                    endControlFlow()
                } else {
                    addStatement("%M { }", materialTheme)
                }
            }
            .endControlFlow()
            .endControlFlow()
            .build()

        val file = FileSpec.builder("", "Main")
            .addFileComment(
                "Generated by ViewForge — do not edit.\n%L",
                "Source: ${project.name.ifBlank { "Project" }}.vforge (schema ${project.schemaVersion})",
            )
            .indent("    ")
            .addFunction(FunSpec.builder("main").addCode(body).build())
            .build()
            .toString()
        return KotlinFormatter.format(file)
    }

    private fun resource(name: String): ByteArray =
        requireNotNull(javaClass.getResourceAsStream("/scaffold/$name")) { "missing scaffold resource: $name" }
            .use { it.readBytes() }
}
