package viewforge.packages.compose.targets

/**
 * The non-Kotlin text files of an exported Compose Desktop project (G5): build scripts, Gradle
 * config, and the wrapper properties. The generated *UI* Kotlin (screens + `Main.kt`) is built
 * structurally with KotlinPoet in [DesktopExporter] (CLAUDE.md rule 4); these build-config files are
 * flat templates because the only user-derived value that ever enters them is the project name, which
 * is reduced to a `[a-z0-9-]` slug ([slug]) so it cannot alter file structure (ADR-019). No user prop
 * values reach these files, so GC-2's injection concern does not apply here.
 *
 * Pinned versions mirror `gradle/libs.versions.toml` — this is the toolchain ViewForge generates and
 * has tested against. They are duplicated as constants because the version catalog is a build-time
 * artifact with no runtime accessor; keep them in lockstep with the catalog on every bump.
 */
internal object GradleScaffold {
    const val KOTLIN_VERSION = "2.1.20" // libs.versions.toml: kotlin
    const val COMPOSE_VERSION = "1.7.3" // libs.versions.toml: compose
    const val GRADLE_VERSION = "8.11.1" // gradle/wrapper/gradle-wrapper.properties (bundled jar)
    const val JVM_TOOLCHAIN = "21" // libs.versions.toml: jdk

    private const val COMPOSE_DEV_REPO = "https://maven.pkg.jetbrains.space/public/p/compose/dev"

    /** `build.gradle.kts` — a minimal runnable Compose Desktop module (`./gradlew run`). */
    fun buildGradle(): String =
        """
        // Generated by ViewForge project scaffold. Safe to edit — this is now your project.
        plugins {
            kotlin("jvm") version "$KOTLIN_VERSION"
            id("org.jetbrains.compose") version "$COMPOSE_VERSION"
            id("org.jetbrains.kotlin.plugin.compose") version "$KOTLIN_VERSION"
        }

        repositories {
            google()
            mavenCentral()
            maven("$COMPOSE_DEV_REPO")
        }

        dependencies {
            implementation(compose.desktop.currentOs)
            // currentOs bundles runtime/foundation/ui + Material 2; the generated screens and Theme
            // use Material 3 (MaterialTheme, Text, Button, ColorScheme, …), which is a separate artifact.
            implementation(compose.material3)
        }

        kotlin {
            jvmToolchain($JVM_TOOLCHAIN)
        }

        compose.desktop {
            application {
                mainClass = "MainKt"
            }
        }
        """.trimIndent() + "\n"

    /** `settings.gradle.kts` — plugin repositories plus the project name. */
    fun settingsGradle(slug: String): String =
        """
        // Generated by ViewForge project scaffold.
        pluginManagement {
            repositories {
                gradlePluginPortal()
                google()
                mavenCentral()
                maven("$COMPOSE_DEV_REPO")
            }
        }

        rootProject.name = "$slug"
        """.trimIndent() + "\n"

    fun gradleProperties(): String =
        """
        kotlin.code.style=official
        org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
        org.gradle.caching=true
        """.trimIndent() + "\n"

    fun gitignore(): String =
        """
        .gradle/
        build/
        !gradle/wrapper/gradle-wrapper.jar
        .idea/
        *.iml
        .DS_Store
        """.trimIndent() + "\n"

    /** `gradle/wrapper/gradle-wrapper.properties`, pinned to the [GRADLE_VERSION] the bundled jar expects. */
    fun wrapperProperties(): String =
        """
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
        networkTimeout=10000
        validateDistributionUrl=true
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        """.trimIndent() + "\n"

    /** `README.md` — [name] is shown as prose only (never executed), so it is used verbatim. */
    fun readme(name: String): String =
        """
        # $name

        Generated by [ViewForge](https://viewforge.dev) from `$name.vforge`.

        The composables under `src/main/kotlin` are generated output — regenerate them from the
        editor rather than hand-editing, or they will be overwritten on the next export.

        ## Run

            ./gradlew run
        """.trimIndent() + "\n"

    /**
     * A filesystem/Gradle-safe project name derived from [name]: lowercase, non-alphanumerics folded
     * to single hyphens, trimmed. Falls back to `viewforge-app` when nothing survives (e.g. a name of
     * only punctuation), so `rootProject.name` and the export directory are always valid.
     */
    fun slug(name: String): String = name.lowercase()
        .replace(Regex("[^a-z0-9]+"), "-")
        .trim('-')
        .ifBlank { "viewforge-app" }
}
