package viewforge.packages.compose.targets

/**
 * The non-Kotlin text files of an exported **KMP multi-target** project (ADR-036): the Compose
 * Multiplatform `build.gradle.kts` (a `jvm()` desktop target + an `androidTarget()`), the Android
 * manifest, and the Gradle config. The parallel of [GradleScaffold] for the multiplatform export; the
 * generated *UI* Kotlin (screens in `commonMain`, `Main.kt`, `MainActivity.kt`) is built structurally
 * with KotlinPoet elsewhere ([ComposeEntryPoints], [viewforge.packages.compose.codegen.ComposeCodeGenerator]).
 *
 * As with [GradleScaffold], the only user-derived value that enters is the project name — reduced to a
 * `[a-z0-9-]` [GradleScaffold.slug] (and a valid package via [applicationId]) so it cannot alter file
 * structure (ADR-019); the manifest `android:label` is XML-escaped prose. Pinned versions mirror
 * `gradle/libs.versions.toml` (ADR-036) and are duplicated as constants because the catalog is a
 * build-time artifact with no runtime accessor — keep them in lockstep on every bump.
 *
 * NOTE: the generated Android project is **not** compiled by ViewForge's own build (no Android SDK; the
 * in-process Android compile gate is #219, ADR-038). This scaffold is verified structurally by
 * `MultiplatformExporterTest` here; real Android compilation is proven by #219 / the user's toolchain.
 */
internal object MultiplatformScaffold {
    // Mirror gradle/libs.versions.toml (ADR-036). Compose-Android reuses GradleScaffold.COMPOSE_VERSION.
    const val AGP_VERSION = "8.7.3" // libs.versions.toml: agp
    const val ANDROID_MIN_SDK = "24" // libs.versions.toml: androidMinSdk
    const val ANDROID_COMPILE_SDK = "35" // libs.versions.toml: androidCompileSdk
    const val ANDROID_TARGET_SDK = "35" // libs.versions.toml: androidTargetSdk
    const val ACTIVITY_COMPOSE_VERSION = "1.9.3" // libs.versions.toml: activityCompose

    private const val COMPOSE_DEV_REPO = "https://maven.pkg.jetbrains.space/public/p/compose/dev"

    /**
     * A valid Android `namespace`/`applicationId` derived from [slug]: `dev.viewforge.<segment>`, where the
     * segment folds the slug's hyphens to underscores and prefixes `app_` if it would start with a digit
     * (a package segment cannot begin with a digit), so any project name yields a legal package.
     */
    fun applicationId(slug: String): String {
        val segment = slug.replace('-', '_').let { if (it.firstOrNull()?.isDigit() == true) "app_$it" else it }
        return "dev.viewforge.$segment"
    }

    /** `build.gradle.kts` — a runnable Compose Multiplatform module targeting desktop (`jvm`) and Android. */
    fun buildGradle(slug: String): String {
        val appId = applicationId(slug)
        return """
        // Generated by ViewForge project scaffold. Safe to edit — this is now your project.
        // Desktop: ./gradlew run    Android: ./gradlew installDebug (needs the Android SDK).
        plugins {
            kotlin("multiplatform") version "${GradleScaffold.KOTLIN_VERSION}"
            id("com.android.application") version "$AGP_VERSION"
            id("org.jetbrains.compose") version "${GradleScaffold.COMPOSE_VERSION}"
            id("org.jetbrains.kotlin.plugin.compose") version "${GradleScaffold.KOTLIN_VERSION}"
        }

        repositories {
            google()
            mavenCentral()
            maven("$COMPOSE_DEV_REPO")
        }

        kotlin {
            jvmToolchain(${GradleScaffold.JVM_TOOLCHAIN})
            jvm()
            androidTarget()

            sourceSets {
                commonMain.dependencies {
                    implementation(compose.runtime)
                    implementation(compose.foundation)
                    implementation(compose.material3)
                    implementation(compose.ui)
                }
                jvmMain.dependencies {
                    implementation(compose.desktop.currentOs)
                }
                androidMain.dependencies {
                    implementation("androidx.activity:activity-compose:$ACTIVITY_COMPOSE_VERSION")
                }
            }
        }

        android {
            namespace = "$appId"
            compileSdk = $ANDROID_COMPILE_SDK

            defaultConfig {
                applicationId = "$appId"
                minSdk = $ANDROID_MIN_SDK
                targetSdk = $ANDROID_TARGET_SDK
                versionCode = 1
                versionName = "1.0"
            }

            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_${GradleScaffold.JVM_TOOLCHAIN}
                targetCompatibility = JavaVersion.VERSION_${GradleScaffold.JVM_TOOLCHAIN}
            }
        }

        compose.desktop {
            application {
                mainClass = "MainKt"
            }
        }
        """.trimIndent() + "\n"
    }

    /** `settings.gradle.kts` — plugin repositories (incl. `google()` for AGP) plus the project name. */
    fun settingsGradle(slug: String): String =
        """
        // Generated by ViewForge project scaffold.
        pluginManagement {
            repositories {
                google()
                gradlePluginPortal()
                mavenCentral()
                maven("$COMPOSE_DEV_REPO")
            }
        }

        rootProject.name = "$slug"
        """.trimIndent() + "\n"

    fun gradleProperties(): String =
        """
        kotlin.code.style=official
        org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
        org.gradle.caching=true
        android.useAndroidX=true
        android.nonTransitiveRClass=true
        """.trimIndent() + "\n"

    fun gitignore(): String =
        """
        .gradle/
        build/
        !gradle/wrapper/gradle-wrapper.jar
        .idea/
        *.iml
        .DS_Store
        local.properties
        .cxx/
        """.trimIndent() + "\n"

    /**
     * `src/androidMain/AndroidManifest.xml`. The launcher activity is bound by the **fully-qualified** name
     * `MainActivity` (no leading dot ⇒ Android reads it as an absolute class name, resolving the default-package
     * `MainActivity` that [ComposeEntryPoints.androidMainActivity] emits), while the R class/build use the
     * `namespace` from [buildGradle]. [name] is the app label, XML-escaped so no metacharacter can alter structure.
     */
    fun androidManifest(name: String): String =
        """
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <application
                android:label="${xmlEscape(name.ifBlank { "ViewForge" })}"
                android:theme="@android:style/Theme.Material.Light.NoActionBar">
                <activity
                    android:name="MainActivity"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        """.trimIndent() + "\n"

    /** `README.md` — [name] is prose only (never executed), so it is used verbatim. */
    fun readme(name: String): String =
        """
        # $name

        Generated by [ViewForge](https://viewforge.dev) from `$name.vforge` as a Compose Multiplatform
        project targeting **desktop** and **Android** from shared `commonMain` UI.

        The composables under `src/commonMain/kotlin` are generated output — regenerate them from the
        editor rather than hand-editing, or they will be overwritten on the next export.

        ## Run

            ./gradlew run           # desktop (JVM)
            ./gradlew installDebug  # Android (requires the Android SDK)
        """.trimIndent() + "\n"

    private fun xmlEscape(s: String): String = s
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&apos;")
}
