package viewforge.project

import viewforge.model.FrameworkRef
import viewforge.model.Node
import viewforge.model.NodeId
import viewforge.model.Project
import viewforge.model.Screen
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNull

/**
 * The pure re-open importer (ADR-032, #22): recognise a ViewForge-generated `.kt` via the ownership
 * manifest and reconstruct IR from the sidecar — never by parsing Kotlin — with a fail-loud [ImportFailure]
 * for anything outside the owned set. Managed dirs are built by hand (not via a full export) so each failure
 * mode is isolated.
 */
class ProjectImporterTest {
    private val header = "// Generated by ViewForge — do not edit.\n"

    private fun tempRoot() = Files.createTempDirectory("import")

    private fun demo(name: String = "Demo") = Project(
        id = "proj-1",
        name = name,
        framework = FrameworkRef("viewforge.compose", "1.0.0"),
        screens = listOf(
            Screen(id = "screen-1", name = "Home", root = Node(id = NodeId("n1"), type = "vforge.column")),
        ),
    )

    private fun writeFile(root: Path, relative: String, content: String): Path {
        val file = relative.split('/').fold(root) { acc, seg -> acc.resolve(seg) }
        Files.createDirectories(file.parent)
        Files.writeString(file, content)
        return file
    }

    /** Writes a manifest owning [owned] with the given [screenPaths] into [root]. */
    private fun manifest(root: Path, owned: List<String>, screenPaths: Map<String, String> = emptyMap()) {
        ExportManifestStore.save(ExportManifest(project = "Demo", paths = owned, screenPaths = screenPaths), root)
    }

    @Test
    fun `opens a recognised owned file and reconstructs the project and screen`() {
        val root = tempRoot()
        val kt = writeFile(root, "src/main/kotlin/Home.kt", header + "fun Home() {}")
        ExportManifestStore.saveSidecar(demo(), root)
        manifest(
            root,
            owned = listOf("src/main/kotlin/Home.kt"),
            screenPaths = mapOf(
                "src/main/kotlin/Home.kt" to "screen-1",
            ),
        )

        val result = ProjectImporter.open(kt)
        assertIs<ImportResult.Success>(result)
        assertEquals("proj-1", result.project.id)
        assertEquals("screen-1", result.screenId)
    }

    @Test
    fun `an owned file with no screen mapping opens with a null screen id`() {
        val root = tempRoot()
        val kt = writeFile(root, "Home.kt", header + "fun Home() {}")
        ExportManifestStore.saveSidecar(demo(), root)
        manifest(root, owned = listOf("Home.kt")) // no screenPaths entry

        val result = ProjectImporter.open(kt)
        assertIs<ImportResult.Success>(result)
        assertNull(result.screenId)
    }

    @Test
    fun `a missing file is refused`() {
        val root = tempRoot()
        val result = ProjectImporter.open(root.resolve("nope.kt"))
        assertEquals(ImportFailure.NOT_A_FILE, (result as ImportResult.Failure).kind)
    }

    @Test
    fun `a file without the generated header is refused before anything else`() {
        val root = tempRoot()
        val kt = writeFile(root, "Home.kt", "package acme\nfun Home() {}")
        ExportManifestStore.saveSidecar(demo(), root)
        manifest(root, owned = listOf("Home.kt")) // even fully owned, no header ⇒ not ours

        val result = ProjectImporter.open(kt)
        assertEquals(ImportFailure.NOT_GENERATED, (result as ImportResult.Failure).kind)
    }

    @Test
    fun `a generated file with no ancestor manifest is refused`() {
        val root = tempRoot()
        val kt = writeFile(root, "loose/Home.kt", header + "fun Home() {}")
        val result = ProjectImporter.open(kt)
        assertEquals(ImportFailure.NO_MANIFEST, (result as ImportResult.Failure).kind)
    }

    @Test
    fun `a generated file the manifest does not own is refused`() {
        val root = tempRoot()
        val kt = writeFile(root, "Home.kt", header + "fun Home() {}")
        ExportManifestStore.saveSidecar(demo(), root)
        manifest(root, owned = listOf("Other.kt")) // owns a different file

        val result = ProjectImporter.open(kt)
        assertEquals(ImportFailure.NOT_OWNED, (result as ImportResult.Failure).kind)
    }

    @Test
    fun `a corrupt manifest owns nothing so the file is refused`() {
        val root = tempRoot()
        val kt = writeFile(root, "Home.kt", header + "fun Home() {}")
        writeFile(root, ".viewforge/manifest.json", "{ not valid json ]")

        val result = ProjectImporter.open(kt)
        assertEquals(ImportFailure.NOT_OWNED, (result as ImportResult.Failure).kind)
    }

    @Test
    fun `an owned file with no sidecar is refused`() {
        val root = tempRoot()
        val kt = writeFile(root, "Home.kt", header + "fun Home() {}")
        manifest(root, owned = listOf("Home.kt")) // owned, but no project.vforge written

        val result = ProjectImporter.open(kt)
        assertEquals(ImportFailure.SIDECAR_MISSING, (result as ImportResult.Failure).kind)
    }

    @Test
    fun `a corrupt sidecar is refused and never guessed`() {
        val root = tempRoot()
        val kt = writeFile(root, "Home.kt", header + "fun Home() {}")
        manifest(root, owned = listOf("Home.kt"))
        writeFile(root, ".viewforge/project.vforge", "{ not a project ]")

        val result = ProjectImporter.open(kt)
        assertEquals(ImportFailure.SIDECAR_LOAD_FAILED, (result as ImportResult.Failure).kind)
    }
}
