package viewforge.project

import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * End-to-end safe regeneration on a real temp directory (G10, ADR-029): the manifest is written and read
 * back, ViewForge's own files are replaced, orphans are deleted, and anything unowned blocks the whole run
 * without touching disk.
 */
class RegenerationTest {
    private fun tempRoot() = Files.createTempDirectory("regen")
    private fun text(path: String, content: String) = TextFile(path, content)
    private fun manifestPaths(root: Path) = ExportManifestStore.load(root)?.paths

    @Test
    fun `a first regeneration writes the bundle and records a manifest`() {
        val root = tempRoot()
        val outcome = ProjectExporter.regenerate(
            root,
            listOf(text("Main.kt", "main"), text("HomeScreen.kt", "home")),
            projectName = "Demo",
        )
        assertIs<RegenerationOutcome.Applied>(outcome)
        assertEquals(listOf("Main.kt", "HomeScreen.kt"), outcome.written)
        assertTrue(outcome.deleted.isEmpty())
        assertEquals("main", root.resolve("Main.kt").readText())
        assertEquals(listOf("Main.kt", "HomeScreen.kt"), manifestPaths(root))
    }

    @Test
    fun `re-regenerating replaces owned files and deletes orphans`() {
        val root = tempRoot()
        ProjectExporter.regenerate(root, listOf(text("Main.kt", "v1"), text("OldScreen.kt", "old")), "Demo")

        // The project changed: OldScreen is gone, NewScreen appears, Main is edited.
        val outcome = ProjectExporter.regenerate(
            root,
            listOf(text("Main.kt", "v2"), text("NewScreen.kt", "new")),
            projectName = "Demo",
        )
        assertIs<RegenerationOutcome.Applied>(outcome)
        assertEquals(listOf("OldScreen.kt"), outcome.deleted)
        assertEquals("v2", root.resolve("Main.kt").readText())
        assertTrue(Files.exists(root.resolve("NewScreen.kt")))
        assertFalse(Files.exists(root.resolve("OldScreen.kt")), "the orphaned owned file should be removed")
        assertEquals(listOf("Main.kt", "NewScreen.kt"), manifestPaths(root))
    }

    @Test
    fun `an unowned file at a bundle path blocks the run and nothing is written`() {
        val root = tempRoot()
        // The user hand-authored HomeScreen.kt (no header, no manifest); it must not be overwritten.
        root.resolve("HomeScreen.kt").writeText("hand written")

        val outcome = ProjectExporter.regenerate(
            root,
            listOf(text("Main.kt", "main"), text("HomeScreen.kt", "generated")),
            projectName = "Demo",
        )
        assertIs<RegenerationOutcome.Blocked>(outcome)
        assertEquals(listOf("HomeScreen.kt"), outcome.unowned)
        assertEquals("hand written", root.resolve("HomeScreen.kt").readText()) // untouched
        assertFalse(Files.exists(root.resolve("Main.kt")), "nothing is written when the run is blocked")
        assertNull(manifestPaths(root), "no manifest is written when the run is blocked")
    }

    @Test
    fun `a file carrying the generated header is adopted as owned without a manifest`() {
        val root = tempRoot()
        // A plain earlier export left a header-stamped file but no manifest; regeneration should own it.
        root.resolve("HomeScreen.kt").writeText("// Generated by ViewForge — do not edit.\nold")

        val outcome = ProjectExporter.regenerate(root, listOf(text("HomeScreen.kt", "new")), projectName = "Demo")
        assertIs<RegenerationOutcome.Applied>(outcome)
        assertEquals("new", root.resolve("HomeScreen.kt").readText())
        assertEquals(listOf("HomeScreen.kt"), manifestPaths(root))
    }

    @Test
    fun `regenerationPlan previews without writing`() {
        val root = tempRoot()
        root.resolve("HomeScreen.kt").writeText("hand written")
        val plan = ProjectExporter.regenerationPlan(root, listOf(text("HomeScreen.kt", "x"), text("Main.kt", "y")))
        assertEquals(listOf("HomeScreen.kt"), plan.blocked)
        assertFalse(Files.exists(root.resolve("Main.kt"))) // a dry run writes nothing
        assertNull(manifestPaths(root))
    }

    @Test
    fun `a corrupt manifest loads as null so nothing is treated as owned`() {
        val root = tempRoot()
        val manifest = root.resolve(".viewforge").resolve("manifest.json")
        Files.createDirectories(manifest.parent)
        manifest.writeText("{ not valid json ]")
        assertNull(ExportManifestStore.load(root))
    }
}
