package viewforge.project

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * The pure ownership rules of safe regeneration (G10, ADR-029): given the new bundle, the owned set, and
 * which paths currently exist, [planRegeneration] decides what to write, what stale output to delete, and
 * which unowned files must block the regeneration. No filesystem — the disk state is a predicate.
 */
class RegenerationPlanTest {
    private fun plan(bundle: List<String>, owned: Set<String>, onDisk: Set<String>) =
        planRegeneration(bundle, owned, exists = { it in onDisk })

    @Test
    fun `a first export into an empty directory writes everything and blocks or deletes nothing`() {
        val p = plan(bundle = listOf("Main.kt", "HomeScreen.kt"), owned = emptySet(), onDisk = emptySet())
        assertEquals(listOf("Main.kt", "HomeScreen.kt"), p.toWrite)
        assertTrue(p.blocked.isEmpty())
        assertTrue(p.toDelete.isEmpty())
    }

    @Test
    fun `re-exporting over ViewForge's own prior files is not blocked`() {
        // Both bundle files exist and are owned (in the previous manifest) -> they are simply replaced.
        val p = plan(
            bundle = listOf("Main.kt", "HomeScreen.kt"),
            owned = setOf("Main.kt", "HomeScreen.kt"),
            onDisk = setOf("Main.kt", "HomeScreen.kt"),
        )
        assertTrue(p.blocked.isEmpty())
        assertTrue(p.toDelete.isEmpty())
    }

    @Test
    fun `an owned file the new bundle no longer emits is an orphan to delete`() {
        // OldScreen.kt was ours last time (owned + on disk) but is gone from the new bundle -> delete it.
        val p = plan(
            bundle = listOf("Main.kt"),
            owned = setOf("Main.kt", "OldScreen.kt"),
            onDisk = setOf("Main.kt", "OldScreen.kt"),
        )
        assertEquals(listOf("OldScreen.kt"), p.toDelete)
        assertTrue(p.blocked.isEmpty())
    }

    @Test
    fun `an orphan already gone from disk is not scheduled for deletion`() {
        val p = plan(bundle = listOf("Main.kt"), owned = setOf("Main.kt", "OldScreen.kt"), onDisk = setOf("Main.kt"))
        assertTrue(p.toDelete.isEmpty())
    }

    @Test
    fun `an existing unowned file at a bundle path blocks the regeneration`() {
        // The user authored HomeScreen.kt themselves (exists, not owned) -> we must not overwrite it.
        val p = plan(
            bundle = listOf("Main.kt", "HomeScreen.kt"),
            owned = setOf("Main.kt"),
            onDisk = setOf("Main.kt", "HomeScreen.kt"),
        )
        assertEquals(listOf("HomeScreen.kt"), p.blocked)
    }

    @Test
    fun `a bundle path that does not yet exist is never blocked`() {
        val p = plan(bundle = listOf("New.kt"), owned = emptySet(), onDisk = setOf("Unrelated.kt"))
        assertTrue(p.blocked.isEmpty())
    }

    @Test
    fun `the generated header is recognised as an ownership signal`() {
        assertTrue(ExportManifest.carriesGeneratedHeader("// Generated by ViewForge — do not edit.\nfun X() {}"))
        assertFalse(ExportManifest.carriesGeneratedHeader("package com.acme\n\n// Generated by ViewForge later"))
        assertFalse(ExportManifest.carriesGeneratedHeader("fun handWritten() {}"))
    }
}
