// Generated by ViewForge — do not edit.
// Source: AppBars.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Home
import androidx.compose.material3.BottomAppBar
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.OptIn

@OptIn(ExperimentalMaterial3Api::class)
@Composable
public fun AppBarsScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        TopAppBar(title = {
            Text(text = "Home")
        })
        BottomAppBar {
            Icon(
                imageVector = Icons.Filled.Home,
                contentDescription = "Home",
            )
        }
    }
}
