// Generated by ViewForge — do not edit.
// Source: ButtonShape.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
public fun ButtonShapeScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Button(
            onClick = { /* TODO */ },
            shape = RoundedCornerShape(12.dp),
        ) {
            Text(text = "Rounded")
        }
        Button(
            onClick = { /* TODO */ },
            shape = MaterialTheme.shapes.large,
        ) {
            Text(text = "Themed")
        }
    }
}
