// Generated by ViewForge — do not edit.
// Source: ButtonStates.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun ButtonStatesScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Button(
            onClick = { /* TODO */ },
            enabled = false,
        ) {
            Text(text = "Primary")
        }
        OutlinedButton(
            onClick = { /* TODO */ },
            enabled = false,
        ) {
            Text(text = "Secondary")
        }
        TextButton(
            onClick = { /* TODO */ },
            enabled = true,
        ) {
            Text(text = "Tertiary")
        }
    }
}
