// Generated by ViewForge — do not edit.
// Source: Buttons.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun ButtonsScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        OutlinedButton(onClick = { /* TODO */ }) {
            Text(text = "Outlined")
        }
        TextButton(onClick = { /* TODO */ }) {
            Text(text = "Text")
        }
    }
}
