// Generated by ViewForge — do not edit.
// Source: ComponentNavigation.vforge (schema 6)
import androidx.compose.foundation.layout.Column
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.String
import kotlin.Unit

@Composable
public fun Hub(onNavigate: (String) -> Unit = {}, modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        NavCard(onNavigate = onNavigate)
    }
}
