// Generated by ViewForge — do not edit.
// Source: ComponentState.vforge (schema 5)
import androidx.compose.foundation.layout.Column
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun Directory(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        ProfileCard(title = "Team")
    }
}
