// Generated by ViewForge — do not edit.
// Source: ComponentState.vforge (schema 5)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.String

@Composable
public fun ProfileCard(title: String, modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    val heading = "Members"
    val badges = listOf(
        Badge(label = "Ada"),
        Badge(label = "Grace"),
    )
    Column(modifier = modifier) {
        Text(text = title)
        Text(text = heading)
        badges.forEach { item ->
            Text(text = item.label)
        }
    }
}

public data class Badge(
    public val label: String,
)
