// Generated by ViewForge — do not edit.
// Source: Containers.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Card
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
public fun ContainersScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier.padding(16.dp)) {
        Card {
            Text(text = "In a card")
        }
        HorizontalDivider(thickness = 2.dp)
        Surface {
            Text(text = "On a surface")
        }
    }
}
