// Generated by ViewForge — do not edit.
// Source: Gallery.vforge (schema 1)
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp

@Composable
public fun GalleryScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier.fillMaxSize().padding(24.dp)) {
        Text(
            text = "Photo Gallery",
            color = MaterialTheme.colorScheme.primary,
            style = MaterialTheme.typography.titleLarge,
        )
        Row(
            modifier = Modifier.fillMaxWidth().padding(top = 16.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Button(onClick = { /* TODO */ }) {
                Text(text = "Add")
            }
            Button(onClick = { /* TODO */ }) {
                Text(text = "Sort")
            }
        }
        LazyColumn(modifier = Modifier.fillMaxWidth().padding(top = 16.dp)) {
            item {
                Row(
                    modifier = Modifier.padding(8.dp),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Image(
                        painter = painterResource("assets/hero.png"),
                        contentDescription = "Sunset",
                        modifier = Modifier.size(64.dp),
                        contentScale = ContentScale.Crop,
                    )
                    Column(modifier = Modifier.padding(start = 12.dp)) {
                        Text(
                            text = "Sunset",
                            style = MaterialTheme.typography.titleMedium,
                        )
                        Text(text = "Beach at dusk")
                    }
                }
            }
            item {
                Row(
                    modifier = Modifier.padding(8.dp),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Image(
                        painter = painterResource("assets/icon.png"),
                        contentDescription = "Mountains",
                        modifier = Modifier.size(64.dp),
                        contentScale = ContentScale.Crop,
                    )
                    Column(modifier = Modifier.padding(start = 12.dp)) {
                        Text(
                            text = "Mountains",
                            style = MaterialTheme.typography.titleMedium,
                        )
                        Text(text = "Alpine trail")
                    }
                }
            }
            item {
                Box(
                    modifier = Modifier.size(80.dp).padding(top = 8.dp),
                    contentAlignment = Alignment.Center,
                ) {
                    Text(text = "More coming soon")
                }
            }
        }
    }
}
