// Generated by ViewForge — do not edit.
// Source: Icons.vforge (schema 1)
import androidx.compose.foundation.layout.Row
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun IconsScreen(modifier: Modifier = Modifier) {
    Row(modifier = modifier) {
        Icon(
            imageVector = Icons.Filled.Favorite,
            contentDescription = "Like",
        )
        Icon(
            imageVector = Icons.Filled.Settings,
            contentDescription = null,
        )
    }
}
