// Generated by ViewForge — do not edit.
// Source: ImageAdjust.vforge (schema 1)
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp

@Composable
public fun ImageAdjustScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Image(
            painter = painterResource("assets/photo.png"),
            contentDescription = "Framed",
            modifier = Modifier.size(96.dp),
            alignment = Alignment.BottomEnd,
            alpha = 0.5f,
        )
        Image(
            painter = painterResource("assets/badge.png"),
            contentDescription = null,
            alpha = 0.25f,
        )
    }
}
