// Generated by ViewForge — do not edit.
// Source: Image.vforge (schema 1)
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp

@Composable
public fun ImageScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier.padding(16.dp)) {
        Image(
            painter = painterResource("assets/hero.png"),
            contentDescription = "Hero banner",
            modifier = Modifier.size(120.dp),
            contentScale = ContentScale.Crop,
        )
        Image(
            painter = painterResource("assets/icon.png"),
            contentDescription = null,
        )
    }
}
