// Generated by ViewForge — do not edit.
// Source: Indicators.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.Slider
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun IndicatorsScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Slider(
            value = 0.5f,
            onValueChange = { value -> },
            enabled = false,
        )
        CircularProgressIndicator()
        LinearProgressIndicator()
    }
}
