// Generated by ViewForge — do not edit.
// Source: Interactive.vforge (schema 6)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier

@Composable
public fun Counter(modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    val heading = "Score"
    var count by remember { mutableStateOf(0) }
    var expanded by remember { mutableStateOf(false) }
    Column(modifier = modifier) {
        Text(text = heading)
        Button(onClick = {
            count += 1
            expanded = !expanded
        }) {
            Text(text = "Increment")
        }
        TextButton(onClick = {
            count = 0
        }) {
            Text(text = "Reset")
        }
    }
}
