// Generated by ViewForge — do not edit.
// Source: IntText.vforge (schema 6)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier

@Composable
public fun Tally(modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    var count by remember { mutableStateOf(0) }
    val ratio = 0.5f
    Column(modifier = modifier) {
        Text(text = count.toString())
        Text(text = ratio.toString())
        Button(onClick = {
            count += 1
        }) {
            Text(text = "Add")
        }
    }
}
