// Generated by ViewForge — do not edit.
// Source: Lazy.vforge (schema 1)
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier

@Composable
public fun LazyScreen(modifier: Modifier = Modifier) {
    LazyColumn(
        modifier = modifier.fillMaxSize(),
        verticalArrangement = Arrangement.SpaceBetween,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        item {
            Text(text = "Header")
        }
        item {
            LazyRow(horizontalArrangement = Arrangement.SpaceEvenly) {
                item {
                    Text(text = "A")
                }
                item {
                    Text(text = "B")
                }
            }
        }
    }
}
