// Generated by ViewForge — do not edit.
// Source: Modifiers.vforge (schema 1)
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

@Composable
public fun ModifiersScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier.fillMaxSize()) {
        Box(modifier = Modifier.background(Color(0xFFFF0000))) {
        }
        Box(modifier = Modifier.background(MaterialTheme.colorScheme.primary)) {
        }
        Box(modifier = Modifier.background(Color(0xFF123456))) {
        }
        Box(modifier = Modifier.padding(start = 8.dp, top = 4.dp, end = 8.dp, bottom = 4.dp)) {
        }
        Box(modifier = Modifier.fillMaxWidth()) {
        }
    }
}
