// Generated by ViewForge — do not edit.
// Source: ModifierOrder.vforge (schema 1)
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

@Composable
public fun ModifierOrderScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Box(modifier = Modifier.padding(8.dp).background(Color(0xFF00FF00))) {
        }
        Box(modifier = Modifier.background(Color(0xFF00FF00)).padding(8.dp)) {
        }
    }
}
