// Generated by ViewForge — do not edit.
// Source: Navigation.vforge (schema 6)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.String
import kotlin.Unit

@Composable
public fun Home(onNavigate: (String) -> Unit = {}, modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Button(onClick = {
            onNavigate("scr_details")
        }) {
            Text(text = "Go to details")
        }
    }
}
