// Generated by ViewForge — do not edit.
// Source: NestedComponent.vforge (schema 2)
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun PrimaryButton(modifier: Modifier = Modifier) {
    Button(
        onClick = { /* TODO */ },
        modifier = modifier.fillMaxWidth(),
    ) {
        Text(text = "Click me")
    }
}
