// Generated by ViewForge — do not edit.
// Source: NestedList.vforge (schema 4)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.Int
import kotlin.String
import kotlin.collections.List

@Composable
public fun OrgChart(modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    val departments = listOf(
        Department(name = "Engineering", teams = listOf(
            Team(label = "Core", size = 4),
            Team(label = "Platform", size = 3),
        )),
        Department(name = "Design", teams = listOf(
            Team(label = "Brand", size = 2),
        )),
    )
    Column(modifier = modifier) {
        departments.forEach { item ->
            Text(text = item.name)
            item.teams.forEach { item ->
                Text(text = item.label)
            }
        }
    }
}

public data class Department(
    public val name: String,
    public val teams: List<Team>,
)

public data class Team(
    public val label: String,
    public val size: Int,
)
