// Generated by ViewForge — do not edit.
// Source: ParameterizedComponent.vforge (schema 2)
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.Boolean
import kotlin.String

@Composable
public fun PrimaryButton(
    label: String,
    enabled: Boolean = true,
    modifier: Modifier = Modifier,
) {
    Button(
        onClick = { /* TODO */ },
        modifier = modifier.fillMaxWidth(),
        enabled = enabled,
    ) {
        Text(text = label)
    }
}
