// Generated by ViewForge — do not edit.
// Source: ParameterizedComponent.vforge (schema 2)
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
public fun HomeScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier.fillMaxSize()) {
        PrimaryButton(
            label = "Sign in",
            enabled = false,
        )
        PrimaryButton(
            label = "Cancel",
            modifier = Modifier.padding(8.dp),
        )
    }
}
