// Generated by ViewForge — do not edit.
// Source: Picker.vforge (schema 4)
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowDropDown
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Icon
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.String

@Composable
public fun VenuePicker(modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    val venues = listOf(
        Venue(name = "Grand Hall", city = "Paris"),
        Venue(name = "Sky Dome", city = "Tokyo"),
    )
    Column(modifier = modifier) {
        Box {
            OutlinedTextField(
                value = venues.firstOrNull()?.name.orEmpty(),
                onValueChange = {},
                readOnly = true,
                trailingIcon = { Icon(Icons.Filled.ArrowDropDown, contentDescription = null) },
            )
            DropdownMenu(expanded = false, onDismissRequest = {}) {
                venues.forEach { item ->
                    DropdownMenuItem(
                        text = { Text(item.name) },
                        onClick = {},
                    )
                }
            }
        }
    }
}

public data class Venue(
    public val name: String,
    public val city: String,
)
