// Generated by ViewForge — do not edit.
// Source: Roster.vforge (schema 3)
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.String

@Composable
public fun Roster(modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    val guests = listOf(
        Guest(name = "Ada", role = "Lead"),
        Guest(name = "Grace", role = "Engineer"),
    )
    Column(modifier = modifier) {
        LazyColumn {
            items(guests) { item ->
                Text(text = item.name)
                Text(text = item.role)
            }
        }
    }
}

public data class Guest(
    public val name: String,
    public val role: String,
)
