// Generated by ViewForge — do not edit.
// Source: Responsive.vforge (schema 7)
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
public fun Adaptive(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        BoxWithConstraints {
            val fontSize = if (maxWidth >= 840.dp) {
                20.sp
            } else if (maxWidth >= 600.dp) {
                16.sp
            } else {
                14.sp
            }
            val textAlign = if (maxWidth >= 840.dp) {
                TextAlign.Center
            } else if (maxWidth >= 600.dp) {
                TextAlign.Start
            } else {
                TextAlign.Start
            }
            Text(
                text = "Adaptive",
                fontSize = fontSize,
                textAlign = textAlign,
            )
        }
        Text(
            text = "Fixed",
            fontSize = 14.sp,
        )
    }
}
