// Generated by ViewForge — do not edit.
// Source: Scaffold.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.BottomAppBar
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.OptIn

@OptIn(ExperimentalMaterial3Api::class)
@Composable
public fun ScaffoldScreen(modifier: Modifier = Modifier) {
    Scaffold(
        modifier = modifier,
        topBar = {
            TopAppBar(title = {
                Text(text = "Home")
            })
        },
        bottomBar = {
            BottomAppBar {
                Text(text = "Bottom")
            }
        },
    ) { innerPadding ->
        Column(modifier = Modifier.padding(innerPadding)) {
            Text(text = "Body")
        }
    }
}
