// Generated by ViewForge — do not edit.
// Source: StateBinding.vforge (schema 3)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlin.String

@Composable
public fun Dashboard(modifier: Modifier = Modifier) {
    // TODO: replace with your real data source
    val title = "Team Dashboard"
    val progress = 0.6f
    val members = listOf(
        Member(name = "Ada", role = "Lead"),
        Member(name = "Grace", role = "Engineer"),
    )
    Column(modifier = modifier) {
        Text(text = title)
        Slider(
            value = progress,
            onValueChange = {},
        )
        members.forEach { item ->
            Text(text = item.name)
            Text(text = item.role)
        }
    }
}

public data class Member(
    public val name: String,
    public val role: String,
)
