// Generated by ViewForge — do not edit.
// Source: TextStyling.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.sp

@Composable
public fun TextStylingScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Text(
            text = "Heading",
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center,
        )
        Text(
            text = "A long body that may not fit on one line",
            overflow = TextOverflow.Ellipsis,
            maxLines = 1,
        )
    }
}
