// Generated by ViewForge — do not edit.
// Source: TextEmphasis.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.style.TextDecoration

@Composable
public fun TextEmphasisScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Text(
            text = "Italic underlined",
            fontStyle = FontStyle.Italic,
            textDecoration = TextDecoration.Underline,
        )
        Text(
            text = "Struck through",
            textDecoration = TextDecoration.LineThrough,
        )
    }
}
