// Generated by ViewForge — do not edit.
// Source: TextFields.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun TextFieldsScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        TextField(
            value = "Name",
            onValueChange = { text -> },
        )
        OutlinedTextField(
            value = "Email",
            onValueChange = { text -> },
            enabled = false,
        )
    }
}
