// Generated by ViewForge — do not edit.
// Source: TextSpacing.vforge (schema 1)
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.sp

@Composable
public fun TextSpacingScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Text(
            text = "Spaced Heading",
            fontSize = 20.sp,
            letterSpacing = 2.sp,
            lineHeight = 32.sp,
        )
        Text(
            text = "A body paragraph with generous line height",
            lineHeight = 24.sp,
        )
    }
}
