// Generated by ViewForge — do not edit.
// Source: ThemeWrapper.vforge (schema 1)
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

@Composable
public fun ThemeWrapperScreen(modifier: Modifier = Modifier) {
    Text(
        text = "Themed",
        modifier = modifier,
        color = MaterialTheme.colorScheme.primary,
        style = TextStyle(fontSize = 48.sp, fontWeight = FontWeight(700), lineHeight = 56.sp),
    )
}
