// Generated by ViewForge — do not edit.
// Source: Toggles.vforge (schema 1)
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Checkbox
import androidx.compose.material3.Switch
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
public fun TogglesScreen(modifier: Modifier = Modifier) {
    Row(modifier = modifier) {
        Checkbox(
            checked = true,
            onCheckedChange = { checked -> },
            enabled = false,
        )
        Switch(
            checked = false,
            onCheckedChange = { checked -> },
        )
    }
}
