// Generated by ViewForge — do not edit.
// Source: Weight.vforge (schema 1)
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
public fun WeightScreen(modifier: Modifier = Modifier) {
    Column(modifier = modifier) {
        Text(
            text = "A",
            modifier = Modifier.weight(1.0f),
        )
        Row(modifier = Modifier.weight(2.0f).padding(8.dp)) {
            Box(modifier = Modifier.weight(1.0f)) {
            }
        }
        Box(modifier = Modifier.weight(3.0f)) {
            Text(text = "B")
        }
    }
}
